-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 11:16:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BIBLIOTECA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BIBLIOTECA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BIBLIOTECA` DEFAULT CHARACTER SET utf8 ;
USE `BIBLIOTECA` ;

-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Fianaceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Fianaceiro` (
  `idFianaceiro` INT NOT NULL,
  `Acervo` VARCHAR(45) NOT NULL,
  `Leitor` VARCHAR(45) NOT NULL,
  `Departamento_de_compras` VARCHAR(45) NOT NULL,
  `Salário` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFianaceiro`),
  UNIQUE INDEX `idFianaceiro_UNIQUE` (`idFianaceiro` ASC) VISIBLE,
  UNIQUE INDEX `Acervo_UNIQUE` (`Acervo` ASC) VISIBLE,
  UNIQUE INDEX `Leitor_UNIQUE` (`Leitor` ASC) VISIBLE,
  UNIQUE INDEX `Departamento_de_compras_UNIQUE` (`Departamento_de_compras` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Infraestrutura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Infraestrutura` (
  `idInfraestrutura` INT NOT NULL,
  `Sistemas` VARCHAR(45) NULL,
  `Departamento_juridico` VARCHAR(45) NULL,
  `Estrutura` VARCHAR(45) NULL,
  `Fianaceiro_idFianaceiro` INT NOT NULL,
  PRIMARY KEY (`idInfraestrutura`, `Fianaceiro_idFianaceiro`),
  INDEX `fk_Infraestrutura_Fianaceiro1_idx` (`Fianaceiro_idFianaceiro` ASC) VISIBLE,
  CONSTRAINT `fk_Infraestrutura_Fianaceiro1`
    FOREIGN KEY (`Fianaceiro_idFianaceiro`)
    REFERENCES `BIBLIOTECA`.`Fianaceiro` (`idFianaceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Acervo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Acervo` (
  `idAcervo` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `Editora` VARCHAR(45) NOT NULL,
  `Autor` VARCHAR(45) NOT NULL,
  `Id` VARCHAR(45) NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `Ano_da_Publicaçao` VARCHAR(45) NOT NULL,
  `Disponibilidade` VARCHAR(45) NOT NULL,
  `Infraestrutura_idInfraestrutura` INT NOT NULL,
  `Infraestrutura_Fianaceiro_idFianaceiro` INT NOT NULL,
  PRIMARY KEY (`idAcervo`),
  INDEX `fk_Acervo_Infraestrutura1_idx` (`Infraestrutura_idInfraestrutura` ASC, `Infraestrutura_Fianaceiro_idFianaceiro` ASC) VISIBLE,
  CONSTRAINT `fk_Acervo_Infraestrutura1`
    FOREIGN KEY (`Infraestrutura_idInfraestrutura` , `Infraestrutura_Fianaceiro_idFianaceiro`)
    REFERENCES `BIBLIOTECA`.`Infraestrutura` (`idInfraestrutura` , `Fianaceiro_idFianaceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Funcionarios` (
  `idFuncionarios` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Informaçoes` VARCHAR(45) NULL,
  `CNPJ/PIS` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `Comprovavante_de_Estado` VARCHAR(45) NULL,
  `COmprovante_de_residencia` VARCHAR(45) NULL,
  `Historico_escolar` VARCHAR(45) NULL,
  `Curriculum_lattes` VARCHAR(45) NULL,
  `Salario` VARCHAR(45) NOT NULL,
  `Funcionarioscol` VARCHAR(45) NULL,
  `Fianaceiro_idFianaceiro` INT NOT NULL,
  PRIMARY KEY (`idFuncionarios`, `Fianaceiro_idFianaceiro`),
  INDEX `fk_Funcionarios_Fianaceiro1_idx` (`Fianaceiro_idFianaceiro` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionarios_Fianaceiro1`
    FOREIGN KEY (`Fianaceiro_idFianaceiro`)
    REFERENCES `BIBLIOTECA`.`Fianaceiro` (`idFianaceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Informaçao_de_contato` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Livro` (
  `idLivro` INT NOT NULL,
  `Ano_De_Publicaçao` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descriçao` VARCHAR(45) NULL,
  `Autro` VARCHAR(45) NULL,
  `Editora` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idLivro`, `Cliente_idCliente`),
  INDEX `fk_Livro_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `BIBLIOTECA`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`Livro_has_Acervo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`Livro_has_Acervo` (
  `Livro_idLivro` INT NOT NULL,
  `Acervo_idAcervo` INT NOT NULL,
  PRIMARY KEY (`Livro_idLivro`, `Acervo_idAcervo`),
  INDEX `fk_Livro_has_Acervo_Acervo1_idx` (`Acervo_idAcervo` ASC) VISIBLE,
  INDEX `fk_Livro_has_Acervo_Livro1_idx` (`Livro_idLivro` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_has_Acervo_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `BIBLIOTECA`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_has_Acervo_Acervo1`
    FOREIGN KEY (`Acervo_idAcervo`)
    REFERENCES `BIBLIOTECA`.`Acervo` (`idAcervo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA`.`table1` (
  `idtable1` INT NOT NULL,
  `table1col` VARCHAR(45) NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
